export const demoCategories = [
  {
    id: 1,
    nameMm: "သီတင်းကျွတ်ပွဲတော်",
    nameEn: "Thadingyut Festival",
    slug: "thadingyut-festival",
    description:
      "Myanmar Festival of Lights - celebrating the end of Buddhist Lent with lanterns, candles and traditional performances.",
    posterUrl: "/categories/lanterns_f8e4aa28.jpg",
    status: "ACTIVE",
    sortOrder: 1,
  },
  {
    id: 2,
    nameMm: "သင်္ကြန်ပွဲတော်",
    nameEn: "Thingyan Festival",
    slug: "thingyan-festival",
    description:
      "Myanmar New Year Water Festival - joyful water-pouring celebrations, music, and cultural showcases.",
    posterUrl: "/categories/thingyan2_06241482.jpg",
    status: "ACTIVE",
    sortOrder: 2,
  },
  {
    id: 3,
    nameMm: "ယဉ်ကျေးမှု ည",
    nameEn: "Cultural Night",
    slug: "cultural-night",
    description:
      "Sunmoon University Myanmar Team cultural showcases throughout the academic year.",
    posterUrl: "/categories/campus_7cd4cd72.jpg",
    status: "ACTIVE",
    sortOrder: 3,
  },
] as const;

export const demoEvents = [
  {
    id: 1,
    categoryId: 1,
    slug: "thadingyut-night-2026",
    title: "Thadingyut Night of Lights 2026",
    titleMm: "သီတင်းကျွတ် မီးထွန်းပွဲ ၂၀၂၆",
    description:
      "A magical evening at Sunmoon University celebrating the end of Buddhist Lent with thousands of glowing lanterns, traditional Myanmar dance performances by SMU Myanmar Team members, classical music, and authentic food stalls. Join us as we transform the Asan campus into a sea of light.",
    venue: "Sunmoon University Main Auditorium, Asan Campus",
    posterUrl: "/categories/lanterns_f8e4aa28.jpg",
    startsAt: 1792864800000,
    endsAt: 1792879200000,
    saleStartsAt: 1785542400000,
    saleEndsAt: 1792799940000,
    status: "PUBLISHED",
    category: demoCategories[0],
  },
  {
    id: 2,
    categoryId: 1,
    slug: "lantern-parade-2026",
    title: "Myanmar Lantern Parade & Cultural Showcase",
    titleMm: "မြန်မာမီးပုံးပြိုင်ပွဲ",
    description:
      "A vibrant lantern parade across Sunmoon Asan campus followed by a cultural showcase highlighting Myanmar traditional craftsmanship, lantern-making workshops, and a closing ceremony with shared offerings.",
    venue: "Sunmoon Central Plaza",
    posterUrl: "/categories/thadingyut2_698d0b15.png",
    startsAt: 1792949400000,
    endsAt: 1792963800000,
    saleStartsAt: 1779753600000,
    saleEndsAt: 1792929600000,
    status: "PUBLISHED",
    category: demoCategories[0],
  },
  {
    id: 3,
    categoryId: 2,
    slug: "thingyan-water-festival-2026",
    title: "Thingyan Water Festival 2026",
    titleMm: "သင်္ကြန် ရေပက်ပွဲတော် ၂၀၂၆",
    description:
      "Welcome the Myanmar New Year with the joyful water festival on the Sunmoon campus. Live Myanmar pop performances, traditional Thingyan dances, water blessing stations, Mont Lone Yay Paw and traditional Myanmar snacks, plus a special student photo contest.",
    venue: "Sunmoon Sports Field, Asan Campus",
    posterUrl: "/categories/thingyan_6265cf28.jpg",
    startsAt: 1776074400000,
    endsAt: 1776099600000,
    saleStartsAt: 1769904000000,
    saleEndsAt: 1776038340000,
    status: "PUBLISHED",
    category: demoCategories[1],
  },
  {
    id: 4,
    categoryId: 2,
    slug: "thingyan-cultural-stage-2026",
    title: "Thingyan Cultural Stage Night",
    titleMm: "သင်္ကြန် ယဉ်ကျေးမှု ည",
    description:
      "A traditional Myanmar music and stage performance evening hosted by SMU Myanmar Team. Includes Hsaing Waing ensemble, Anyeint comedy theatre, classical Myanmar dance, and a finale fireworks display.",
    venue: "Sunmoon Grand Hall",
    posterUrl: "/categories/thingyan2_06241482.jpg",
    startsAt: 1776191400000,
    endsAt: 1776204000000,
    saleStartsAt: 1769904000000,
    saleEndsAt: 1776168000000,
    status: "PUBLISHED",
    category: demoCategories[1],
  },
  {
    id: 5,
    categoryId: 3,
    slug: "myanmar-night-2026",
    title: "Sunmoon Myanmar Night 2026",
    titleMm: "ဆန်းမွန် မြန်မာည ၂၀၂၆",
    description:
      "The flagship annual showcase by Sunmoon University Myanmar Team. A 3-hour curated cultural evening featuring traditional dance, modern Myanmar music, fashion show of regional costumes, and an after-party with Myanmar street food.",
    venue: "Sunmoon Performing Arts Center",
    posterUrl: "/categories/campus_7cd4cd72.jpg",
    startsAt: 1780855200000,
    endsAt: 1780869600000,
    saleStartsAt: 1775001600000,
    saleEndsAt: 1780790340000,
    status: "PUBLISHED",
    category: demoCategories[2],
  },
] as const;
